package ec.gob.bsg.accesobsgservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0.redhat-610379
 * 2014-09-04T17:27:16.313-05:00
 * Generated source version: 2.7.0.redhat-610379
 * 
 */
@WebService(targetNamespace = "http://bsg.gob.ec/AccesoBSGService", name = "One")
@XmlSeeAlso({ObjectFactory.class})
public interface One {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "execute", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "ec.gob.bsg.accesobsgservice.Execute")
    @WebMethod
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "ec.gob.bsg.accesobsgservice.ExecuteResponse")
    public ec.gob.bsg.accesobsgservice.RetornoOne execute(
        @WebParam(name = "A", targetNamespace = "")
        java.lang.String a
    );
}
