package ec.gob.bsg.accesobsgservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0.redhat-610379
 * 2014-09-04T17:27:16.317-05:00
 * Generated source version: 2.7.0.redhat-610379
 * 
 */
@WebServiceClient(name = "OneService", 
                  wsdlLocation = "file:/home/pazfernando/jbdevstudio_testfuse_workspace/fuse-ws/src/main/resources/wsdl/One.wsdl",
                  targetNamespace = "http://bsg.gob.ec/AccesoBSGService") 
public class OneService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bsg.gob.ec/AccesoBSGService", "OneService");
    public final static QName OnePort = new QName("http://bsg.gob.ec/AccesoBSGService", "OnePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/pazfernando/jbdevstudio_testfuse_workspace/fuse-ws/src/main/resources/wsdl/One.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OneService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/pazfernando/jbdevstudio_testfuse_workspace/fuse-ws/src/main/resources/wsdl/One.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OneService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OneService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OneService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OneService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OneService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OneService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns One
     */
    @WebEndpoint(name = "OnePort")
    public One getOnePort() {
        return super.getPort(OnePort, One.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns One
     */
    @WebEndpoint(name = "OnePort")
    public One getOnePort(WebServiceFeature... features) {
        return super.getPort(OnePort, One.class, features);
    }

}
